language: ruby
rvm:
  - 2.3.1
bundler_args: --without development production --deployment --jobs=3 --retry=3
cache: bundler
notifications:
  slack:
    secure: u7QbRTOuAgAxw3He7E7agWcGH7W5BW1n8U+lpIwOrJGqbRbisbBio0a8Iq6vj1rQM8XPzETX20j9+oXUjTOTgWoTaRnGmUAKtkRHfdSoDKUH0iUQBoGh4CofkIGzYv2wOt+PQV/EObkecrD9xKmfVzwQqlyfChOcRPXwUYh82H2mwqD91m1xEXkbo5Wjr/ermO4wAlcJbq1bm4TmkkZWpazorJBNh+tWXeT2zYe+/lTed+renLtf/IAmPPKR5IGyQMEgs6PZyiOLTU+cwkUFasFwIqFWWjCHfIdG7SagWf62WKxcJ6FYO8c+5k4yADerVB1pHprSGTXKZ91TJ9d3/fqSFrYV5UlwOQ35QYD2tD4Csw/nRx5ITsVoGXsWU+cR0hsa9QVOnc4J993Ytgt/9c7Sr0J9SfIkiqToFes5dic3985MRzrSU2uNCgwkYReeqkR1NODZZTNEwHgPqiVG0zxVzedQQz5FWa4SASKeUnvqU5ABHPzsjoSFk7RCeIAq/9dV+OC2FVML88tUw6oH0R1gB8ohTLDFzvAsEsdTvPpaWaSBR6sRA8noDtDyPrtG0txujx4U2C4oT3iFlkujIKfjLctCUgMkVriLhPo/1G1PaxdoOZpgFtboSuNE1auYqiLRhH1HznxCecQZw+MSC4dWQ6UIUEiSZe/Bdh2dXUg=
